<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dispatcher</name>

  <version>0.4.4</version>
    <description>
    Qt-based ROS 2 application for launching and monitoring
    ROS nodes and arbitrary processes.
  </description>

  <maintainer email="kwehage@jpl.nasa.gov">Kristopher Wehage</maintainer>
  <maintainer email="daniel.pastor.moreno@jpl.nasa.gov">Daniel Pastor</maintainer>

  <author email="Dennis.Wai@jpl.nasa.gov">Dennis Wai</author>
  <author>Alex Brinkman</author>
  <author email="Dennis.Wai@jpl.nasa.gov">Preston Rogers</author>
  
  <license>Apache-2.0</license>

  <url type="repository">
    https://github.com/nasa-jpl/dispatcher
  </url>
  <url type="bugtracker">
    https://github.com/nasa-jpl/dispatcher/issues
  </url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>builtin_interfaces</depend>

  <depend>yaml-cpp</depend>
  <depend>qtbase5-dev</depend>
  <depend>libqt5-opengl-dev</depend>
  
  <exec_depend>tmux</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
