workspace: .

# When a configuration is selected in dispatcher, if this is set to true,
# then processes that are not defined for the specific configuration
# will be hidden (instead of grayed out). [true, false]
hide_unconfigured_processes: true

variables:
  - name: FCAT_LOOP_RATE_HZ
    choices:
    - 1000
    - 500
    - 250
    - 100


configurations:
  - name: online
    icon: :/icons/wifi.png
  - name: offline
    icon: :/icons/wifi-no.png

nodes:

  - name: ping-google-ip
    type: shell
    configurations:
    - name: online
      cmd: ping 8.8.8.8
    - name: offline
      cmd: ping 8.8.4.4
    start_checked: true

  - name: ping-Cloudflare-ip
    type: shell
    configurations:
    - name: offline
      cmd: ping 1.1.1.1
    start_checked: true

  - name: ping-OpenDNS-ip
    type: shell
    configurations:
    - name: offline
      cmd: ping 208.67.222.222
    start_checked: true

  - name: category
    type: category
    items:
      - name: ping-google-com
        type: shell
        configurations:
        - name: offline
          cmd: ping google.com
        start_checked: true
      - name: pingB
        type: shell
        configurations:
        - name: offline
          cmd: ping google.com
        start_checked: true
      - name: pingC
        type: shell
        configurations:
        - name: online
          cmd: ping google.com
        - name: offline
          cmd: ping google.com
        start_checked: true


scripts:

  - name: htop
    cmd: htop
    icon: :/icons/terminal.png
    row: 0
    column: 1
    use_terminal: true

  - name: rqt_graph
    cmd: ros2 run rqt_graph rqt_graph &
    row: 1
    column: 0
    use_terminal: false

  - name: print_loop_rate
    configurations:
    - name: online
      # $FCAT_LOOP_RATE_HZ would be replaced with one of the aforementioned choices before this cmd string is executed 
      cmd: cat /etc/hostname && echo $FCAT_LOOP_RATE_HZ
      hostname: google.com
    - name: offline
      cmd: cat /etc/hostname  && echo $FCAT_LOOP_RATE_HZ
    row: 0
    column: 0
    use_terminal: false
