workspace: .

configurations:
  - name: online
    environment_variables:
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp 
      CYCLONEDDS_URI: /etc/cyclonedds_online.xml
  - name: offline
    environment_variables:
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp 
      CYCLONEDDS_URI: /etc/cyclonedds_offline.xml

# default environment variables used for all configurations if not provided
# in configurations block above, a hidden configuration called 'all' will be used
# as a fallback when configuration specific environment variables are not provided
environment_variables:
  RMW_IMPLEMENTATION: rmw_cyclonedds_cpp 
  CYCLONEDDS_URI: /etc/cyclonedds.xml

nodes:
  - name: fcat
    ros_nodes:
    - namespace: /fcat
      name: fcat
    configurations:
    - name: online
      cmd: ros2 launch install/asimov_bringup/share/asimov_bringup/launch/fcat_online.py
      hostname: asimov-dev.jpl.nasa.gov 

      # Optionally specify username, if username is specified, dispatcher
      #   issues ssh commands as 'ssh username@hostname "command"'; otherwise dispatcher
      #   uses the syntax 'ssh hostname "command"':
      # user: admin 

    - name: offline
      cmd: ros2 launch install/asimov_bringup/share/asimov_bringup/launch/fcat_offline.py
    start_checked: true

  - name: commander
    namespace: /commander
    node_name: commander
    cmd: ros2 run commander commander
    start_checked: true
    stop_tmux_cmd: "C-D"


# Scripts can also be defined to run on specific configurations or hosts
scripts:

  - name: kst
    cmd: kst2 &
    icon: :/icons/plot.png
    row: 0
    column: 0
    use_terminal: false

  - name: htop
    configurations:
    - name: online
      hostname: asimov-dev.jpl.nasa.gov 
      cmd: htop
    - name: offline
      cmd: htop
    icon: :/icons/terminal.png
    row: 0
    column: 1
    use_terminal: true

  - name: rqt_graph
    cmd: ros2 run rqt_graph rqt_graph &
    row: 1
    column: 0
    use_terminal: false

