name: CI
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:jazzy-ros-base
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-build

  test:
    needs: build
    runs-on: ubuntu-latest
    container: ros:jazzy-ros-base
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-build
      - name: colcon test
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon test --base-paths . --packages-select dispatcher
      - name: colcon test-result --verbose
        if: always()
        shell: bash
        run: colcon test-result --verbose
